from animator.graphics.color import BLACK as BLACK
from animator.graphics.color import BLUE as BLUE
from animator.graphics.color import CYAN as CYAN
from animator.graphics.color import GRAY as GRAY
from animator.graphics.color import GREEN as GREEN
from animator.graphics.color import LIME as LIME
from animator.graphics.color import MAGENTA as MAGENTA
from animator.graphics.color import MAROON as MAROON
from animator.graphics.color import NAVY as NAVY
from animator.graphics.color import OLIVE as OLIVE
from animator.graphics.color import ORANGE as ORANGE
from animator.graphics.color import PURPLE as PURPLE
from animator.graphics.color import RED as RED
from animator.graphics.color import SILVER as SILVER
from animator.graphics.color import TEAL as TEAL
from animator.graphics.color import TRANSPARENT as TRANSPARENT
from animator.graphics.color import WHITE as WHITE
from animator.graphics.color import YELLOW as YELLOW
from animator.graphics.color import color as color
from animator.graphics.color import lerp_color as lerp_color
from animator.graphics.Context2d import Context2d as Context2d
from animator.graphics.font_style import FontStyle as FontStyle
from animator.graphics.font_style import TextStyle as TextStyle
from animator.graphics.gradient import Gradient as Gradient
from animator.graphics.shader import Shader as Shader
from animator.graphics.shader import ShaderBlender as ShaderBlender
from animator.graphics.style import Style as Style
